baseURL = '/'
languageCode = 'en-us'
title = 'jacksons notes'
theme = 'terminal'

[params]
themeColor="green"
[languages]
  [languages.en]
    title="jackson's notes"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    copyright="&copy; 2022 jacksonrakena"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "jackson@system:~/notes"
